- name: Run config with letsencrypt
  ansible.builtin.include_tasks: letsencrypt.yml
  when: nginx_site_letsencrypt | bool

- name: Run config without letsencrypt
  ansible.builtin.include_tasks: regular_site.yml
  when: not nginx_site_letsencrypt
