- name: Check if certificate exists
  ansible.builtin.stat:
    path: "{{ nginx_site_cert }}"
  register: cert
  when: nginx_site_cert is defined

- name: create site without SSL
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: "{{ nginx_site_dir }}/{{ nginx_site_name }}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  vars:
    nginx_site_ssl: false
  notify: nginx_site Test config
  when: nginx_site_cert is not defined or cert.stat.exists is not defined or not cert.stat.exists

- name: Create SSL site
  ansible.builtin.template:
    src: site.conf.j2
    dest: "{{ nginx_site_dir }}/{{ nginx_site_name }}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  vars:
    nginx_site_ssl: true
  notify: nginx_site Test config
  when: nginx_site_cert is defined and cert.stat.exists is defined and cert.stat.exists
