- name: check if certificate exists
  stat: path="{{ nginx_site_cert }}"
  register: cert
- name: create site without SSL
  template:
    src: site.conf.j2
    dest: "{{ nginx_site_dir }}/{{ nginx_site_name }}.conf"
    owner: root
    group: root
  vars:
    nginx_site_ssl: false
  notify: test nginx config
  when: cert.stat.exists is not defined or not cert.stat.exists
- name: create SSL site
  template:
    src: site.conf.j2
    dest: "{{ nginx_site_dir }}/{{ nginx_site_name }}.conf"
    owner: root
    group: root
  vars:
    nginx_site_ssl: true
  notify: test nginx config
  when: cert.stat.exists is defined and cert.stat.exists
