- name: nginx_site Test config
  ansible.builtin.command: /usr/sbin/nginx -t
  notify: nginx_site Reload config

- name: nginx_site Reload config
  ansible.builtin.service:
    name: 'nginx'
    state: 'reloaded'
